# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yeni_gui/uis/giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1024, 718)
        Login.setStyleSheet("background-color : ")
        self.label_logo = QtWidgets.QLabel(Login)
        self.label_logo.setGeometry(QtCore.QRect(250, 40, 501, 271))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_logo.setFont(font)
        self.label_logo.setStyleSheet("QLabel {\n"
"        border-radius: 10px; /* Köşe yarıçapı */\n"
"        background-color: rgb(15, 32, 56); /* Buton arka plan rengi */\n"
"        color: white; /* Yazı rengi */\n"
"        padding: 10px; /* İç boşluk */\n"
"        border: 1px solid black;\n"
"    }\n"
"")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("yeni_gui/uis/src/odakbeyaz.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.combo_lang = QtWidgets.QComboBox(Login)
        self.combo_lang.setGeometry(QtCore.QRect(860, 610, 69, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.combo_lang.setFont(font)
        self.combo_lang.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.combo_lang.setStyleSheet("QComboBox {\n"
"        border-radius: 10px;                 /* Köşe yarıçapı */\n"
"        background-color: lightgrey;     /* Buton arka plan rengi */\n"
"        color: balck;                                 /* Yazı rengi */\n"
"        padding: 10px;                         /* İç boşluk */\n"
"        border: 2px solid grey;             /* Kenarlık */\n"
"    }")
        self.combo_lang.setEditable(False)
        self.combo_lang.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.combo_lang.setFrame(True)
        self.combo_lang.setObjectName("combo_lang")
        self.combo_lang.addItem("")
        self.combo_lang.addItem("")
        self.label_user_icon = QtWidgets.QLabel(Login)
        self.label_user_icon.setGeometry(QtCore.QRect(340, 390, 50, 50))
        self.label_user_icon.setText("")
        self.label_user_icon.setPixmap(QtGui.QPixmap("yeni_gui/uis/src/user.png"))
        self.label_user_icon.setScaledContents(True)
        self.label_user_icon.setObjectName("label_user_icon")
        self.label_password_icon = QtWidgets.QLabel(Login)
        self.label_password_icon.setGeometry(QtCore.QRect(340, 460, 50, 50))
        self.label_password_icon.setText("")
        self.label_password_icon.setPixmap(QtGui.QPixmap("yeni_gui/uis/src/password.png"))
        self.label_password_icon.setScaledContents(True)
        self.label_password_icon.setObjectName("label_password_icon")
        self.label_4 = QtWidgets.QLabel(Login)
        self.label_4.setGeometry(QtCore.QRect(340, 390, 341, 51))
        self.label_4.setStyleSheet("background-color : lightgrey ; border-radius: 10")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Login)
        self.label_5.setGeometry(QtCore.QRect(340, 460, 341, 51))
        self.label_5.setStyleSheet("background-color : lightgrey ; border-radius: 10")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.lineEdit_username = QtWidgets.QLineEdit(Login)
        self.lineEdit_username.setGeometry(QtCore.QRect(400, 390, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_username.setStyleSheet("QLineEdit {\n"
"    background-color: lightgrey;  /* Arka plan rengi */\n"
"    border: 1px solid lightgrey;  /* Kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px;  /* Kenarları yuvarlatmak isterseniz */\n"
"}\n"
"")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(Login)
        self.lineEdit_password.setGeometry(QtCore.QRect(400, 460, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"    background-color: lightgrey;  /* Arka plan rengi */\n"
"    border: 1px solid lightgrey;  /* Kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px;  /* Kenarları yuvarlatmak isterseniz */\n"
"}\n"
"")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.button_enter = QtWidgets.QPushButton(Login)
        self.button_enter.setGeometry(QtCore.QRect(580, 570, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_enter.setFont(font)
        self.button_enter.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"        border-radius: 10px; /* Köşe yarıçapı */\n"
"       background-color :green; /* Buton arka plan rengi */\n"
"        color: white; /* Yazı rengi */\n"
"        padding: 10px; /* İç boşluk */\n"
"        border: 2px solid black;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: darkgreen; /* Basılı olduğunda arka plan rengi */\n"
"    }")
        self.button_enter.setObjectName("button_enter")
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_logo.raise_()
        self.combo_lang.raise_()
        self.label_user_icon.raise_()
        self.label_password_icon.raise_()
        self.lineEdit_username.raise_()
        self.lineEdit_password.raise_()
        self.button_enter.raise_()

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.combo_lang.setItemText(0, _translate("Login", "EN"))
        self.combo_lang.setItemText(1, _translate("Login", "TR"))
        self.lineEdit_username.setPlaceholderText(_translate("Login", "Kullanıcı Adı"))
        self.lineEdit_password.setPlaceholderText(_translate("Login", "Şifre"))
        self.button_enter.setText(_translate("Login", "Giriş"))
